services:
  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "3200:3200"
    volumes:
      - ./backend:/app
      - node_modules:/app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf  # Ensure this maps a file to a file
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  node_modules: