services:
  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "3200:3200"
    volumes:
      - ./backend:/app
      - node_modules:/app/node_modules  # Preserve node_modules in a separate volume
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  node_modules:  # Declare a named volume for node_modules