version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3200:3200"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./product_recognition.py:/app/product_recognition.py
      - ./yolov5:/app/yolov5  # Assuming YOLOv5 is used for object detection
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    working_dir: /app/backend
    command: sh -c "npm install && node init-db.js && node server.js"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
